# Generated by Django 5.1.1 on 2024-09-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('employeeName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('designationModels', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
