# Generated by Django 5.1.1 on 2024-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Fake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.DecimalField(decimal_places=2.0, default=0.0, max_digits=10.0, null=True)),
                ('product_description', models.TextField(null=True)),
                ('product_rating', models.DecimalField(decimal_places=2.0, max_digits=3.0, null=True)),
                ('product_deler', models.TextField(max_length=200, null=True)),
                ('product_stock', models.IntegerField(null=True)),
            ],
        ),
    ]
