# Generated by Django 5.1.1 on 2024-11-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_FRAMEWORK_SERVICE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_fake',
            name='product_stock',
        ),
        migrations.AddField(
            model_name='products_fake',
            name='product_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products_fake',
            name='product_image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
