# Generated by Django 5.1.1 on 2024-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST_FRAMEWORK_SERVICE', '0002_remove_products_fake_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_fake',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products_fake',
            name='product_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
